// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::LocateReplyHeader_1_0", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopLocateReplyHeader10 struct {
	__goidl__.IdlObject
	RequestId uint32 `json:"RequestId"`
	LocateStatus uint32 `json:"LocateStatus"`
}

//noinspection GoSnakeCaseUsage
const GiopLocateReplyHeader10Id_Const = "IDL:omg.org/GIOP/LocateReplyHeader_1_0:1.0"

func (self *GiopLocateReplyHeader10) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopLocateReplyHeader10) GoString() string {
	return self.String()
}

func (self *GiopLocateReplyHeader10) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.RequestId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlEnum)
	self.LocateStatus, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateReplyHeader10) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateReplyHeader10) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.RequestId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlEnum)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.LocateStatus)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopLocateReplyHeader10_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopLocateReplyHeader10Helper = GiopLocateReplyHeader10_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopLocateReplyHeader10Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopLocateReplyHeader10.go",
			func() __goidl__.IIdlObject {
				return &GiopLocateReplyHeader10{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopLocateReplyHeader10{}
			},
			__reflect__.TypeOf((*GiopLocateReplyHeader10)(nil))))
}
