// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::LocateReplyHeader_1_1", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopLocateReplyHeader11 struct {
	GiopLocateReplyHeader10
}

//noinspection GoSnakeCaseUsage
const GiopLocateReplyHeader11Id_Const = "IDL:GIOP/LocateReplyHeader_1_1:1.0"

func (self *GiopLocateReplyHeader11) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopLocateReplyHeader11) GoString() string {
	return self.String()
}

func (self *GiopLocateReplyHeader11) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopLocateReplyHeader10.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateReplyHeader11) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateReplyHeader11) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopLocateReplyHeader10.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopLocateReplyHeader11_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopLocateReplyHeader11Helper = GiopLocateReplyHeader11_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopLocateReplyHeader11Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopLocateReplyHeader11.go",
			func() __goidl__.IIdlObject {
				return &GiopLocateReplyHeader11{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopLocateReplyHeader11{}
			},
			__reflect__.TypeOf((*GiopLocateReplyHeader11)(nil))))
}
