// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goIdlIop__ "github.com/bhbosman/goIdlIop"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::ReplyHeader_1_0", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopReplyHeader10 struct {
	__goidl__.IdlObject
	ServiceContext __goIdlIop__.IopServiceContextList `json:"ServiceContext"`
	RequestId uint32 `json:"RequestId"`
	ReplyStatus uint32 `json:"ReplyStatus"`
}

//noinspection GoSnakeCaseUsage
const GiopReplyHeader10Id_Const = "IDL:omg.org/GIOP/ReplyHeader_1_0:1.0"

func (self *GiopReplyHeader10) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopReplyHeader10) GoString() string {
	return self.String()
}

func (self *GiopReplyHeader10) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ServiceContext.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.RequestId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlEnum)
	self.ReplyStatus, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopReplyHeader10) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopReplyHeader10) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ServiceContext.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.RequestId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlEnum)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.ReplyStatus)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopReplyHeader10_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopReplyHeader10Helper = GiopReplyHeader10_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopReplyHeader10Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopReplyHeader10.go",
			func() __goidl__.IIdlObject {
				return &GiopReplyHeader10{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopReplyHeader10{}
			},
			__reflect__.TypeOf((*GiopReplyHeader10)(nil))))
}
