// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goIdlIop__ "github.com/bhbosman/goIdlIop"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::LocateRequestHeader_1_0", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopLocateRequestHeader10 struct {
	__goidl__.IdlObject
	RequestId uint32 `json:"RequestId"`
	ObjectKey __goIdlIop__.IopObjectKey `json:"ObjectKey"`
}

//noinspection GoSnakeCaseUsage
const GiopLocateRequestHeader10Id_Const = "IDL:omg.org/GIOP/LocateRequestHeader_1_0:1.0"

func (self *GiopLocateRequestHeader10) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopLocateRequestHeader10) GoString() string {
	return self.String()
}

func (self *GiopLocateRequestHeader10) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.RequestId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ObjectKey.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader10) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader10) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.RequestId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ObjectKey.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopLocateRequestHeader10_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopLocateRequestHeader10Helper = GiopLocateRequestHeader10_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopLocateRequestHeader10Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopLocateRequestHeader10.go",
			func() __goidl__.IIdlObject {
				return &GiopLocateRequestHeader10{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopLocateRequestHeader10{}
			},
			__reflect__.TypeOf((*GiopLocateRequestHeader10)(nil))))
}
