// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::FragmentHeader_1_3", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopFragmentHeader13 struct {
	GiopFragmentHeader12
}

//noinspection GoSnakeCaseUsage
const GiopFragmentHeader13Id_Const = "IDL:GIOP/FragmentHeader_1_3:1.0"

func (self *GiopFragmentHeader13) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopFragmentHeader13) GoString() string {
	return self.String()
}

func (self *GiopFragmentHeader13) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopFragmentHeader12.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopFragmentHeader13) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopFragmentHeader13) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopFragmentHeader12.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopFragmentHeader13_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopFragmentHeader13Helper = GiopFragmentHeader13_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopFragmentHeader13Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopFragmentHeader13.go",
			func() __goidl__.IIdlObject {
				return &GiopFragmentHeader13{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopFragmentHeader13{}
			},
			__reflect__.TypeOf((*GiopFragmentHeader13)(nil))))
}
