// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::MessageHeader_1_1", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopMessageHeader11 struct {
	__goidl__.IdlObject
	Magic [4]byte `json:"Magic"`
	GiopVersion GiopVersion `json:"GiopVersion"`
	Flags byte `json:"Flags"`
	MessageType byte `json:"MessageType"`
	MessageSize uint32 `json:"MessageSize"`
}

//noinspection GoSnakeCaseUsage
const GiopMessageHeader11Id_Const = "IDL:omg.org/GIOP/MessageHeader_1_1:1.0"

func (self *GiopMessageHeader11) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopMessageHeader11) GoString() string {
	return self.String()
}

func (self *GiopMessageHeader11) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(CharType)
	self.Magic, err = GiopMagicnHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.GiopVersion.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.Flags, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MessageType, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.MessageSize, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopMessageHeader11) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopMessageHeader11) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(CharType)
	err = GiopMagicnHelper.Write(stream, self.Magic)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.GiopVersion.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.Flags)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MessageType)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.MessageSize)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopMessageHeader11_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopMessageHeader11Helper = GiopMessageHeader11_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopMessageHeader11Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopMessageHeader11.go",
			func() __goidl__.IIdlObject {
				return &GiopMessageHeader11{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopMessageHeader11{}
			},
			__reflect__.TypeOf((*GiopMessageHeader11)(nil))))
}
