// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::RequestHeader_1_3", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopRequestHeader13 struct {
	GiopRequestHeader12
}

//noinspection GoSnakeCaseUsage
const GiopRequestHeader13Id_Const = "IDL:GIOP/RequestHeader_1_3:1.0"

func (self *GiopRequestHeader13) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopRequestHeader13) GoString() string {
	return self.String()
}

func (self *GiopRequestHeader13) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopRequestHeader12.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopRequestHeader13) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopRequestHeader13) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopRequestHeader12.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopRequestHeader13_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopRequestHeader13Helper = GiopRequestHeader13_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopRequestHeader13Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopRequestHeader13.go",
			func() __goidl__.IIdlObject {
				return &GiopRequestHeader13{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopRequestHeader13{}
			},
			__reflect__.TypeOf((*GiopRequestHeader13)(nil))))
}
