// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"

// Enum declaration: "GIOP::LocateStatusType_1_0", generatedBy by: "WriteEnumDcl"
type GiopLocateStatusType10 uint32

//noinspection GoUnusedConst
const (
	GiopLocateStatusType10UnknownObject GiopLocateStatusType10 = 0
	GiopLocateStatusType10ObjectHere    GiopLocateStatusType10 = 1
	GiopLocateStatusType10ObjectForward GiopLocateStatusType10 = 2
)

//noinspection GoSnakeCaseUsage
type GiopLocateStatusType10_Helper struct {
}

//noinspection GoSnakeCaseUsage
const GiopLocateStatusType10Id_Const = "IDL:omg.org/GIOP/LocateStatusType_1_0:1.0"

func (self GiopLocateStatusType10_Helper) Id() string {
	return GiopLocateStatusType10Id_Const
}

func (self GiopLocateStatusType10_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self GiopLocateStatusType10_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var GiopLocateStatusType10Helper = GiopLocateStatusType10_Helper{}

func init() {
}
