// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::LocateRequestHeader_1_3", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopLocateRequestHeader13 struct {
	GiopLocateRequestHeader12
}

//noinspection GoSnakeCaseUsage
const GiopLocateRequestHeader13Id_Const = "IDL:GIOP/LocateRequestHeader_1_3:1.0"

func (self *GiopLocateRequestHeader13) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopLocateRequestHeader13) GoString() string {
	return self.String()
}

func (self *GiopLocateRequestHeader13) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopLocateRequestHeader12.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader13) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader13) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopLocateRequestHeader12.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopLocateRequestHeader13_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopLocateRequestHeader13Helper = GiopLocateRequestHeader13_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopLocateRequestHeader13Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopLocateRequestHeader13.go",
			func() __goidl__.IIdlObject {
				return &GiopLocateRequestHeader13{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopLocateRequestHeader13{}
			},
			__reflect__.TypeOf((*GiopLocateRequestHeader13)(nil))))
}
