// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::FragmentHeader_1_2", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopFragmentHeader12 struct {
	__goidl__.IdlObject
	RequestId uint32 `json:"RequestId"`
}

//noinspection GoSnakeCaseUsage
const GiopFragmentHeader12Id_Const = "IDL:omg.org/GIOP/FragmentHeader_1_2:1.0"

func (self *GiopFragmentHeader12) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopFragmentHeader12) GoString() string {
	return self.String()
}

func (self *GiopFragmentHeader12) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.RequestId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopFragmentHeader12) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopFragmentHeader12) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.RequestId)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopFragmentHeader12_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopFragmentHeader12Helper = GiopFragmentHeader12_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopFragmentHeader12Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopFragmentHeader12.go",
			func() __goidl__.IIdlObject {
				return &GiopFragmentHeader12{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopFragmentHeader12{}
			},
			__reflect__.TypeOf((*GiopFragmentHeader12)(nil))))
}
