// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::LocateRequestHeader_1_1", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopLocateRequestHeader11 struct {
	GiopLocateRequestHeader10
}

//noinspection GoSnakeCaseUsage
const GiopLocateRequestHeader11Id_Const = "IDL:GIOP/LocateRequestHeader_1_1:1.0"

func (self *GiopLocateRequestHeader11) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopLocateRequestHeader11) GoString() string {
	return self.String()
}

func (self *GiopLocateRequestHeader11) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopLocateRequestHeader10.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader11) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopLocateRequestHeader11) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopLocateRequestHeader10.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopLocateRequestHeader11_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopLocateRequestHeader11Helper = GiopLocateRequestHeader11_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopLocateRequestHeader11Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopLocateRequestHeader11.go",
			func() __goidl__.IIdlObject {
				return &GiopLocateRequestHeader11{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopLocateRequestHeader11{}
			},
			__reflect__.TypeOf((*GiopLocateRequestHeader11)(nil))))
}
