// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::ReplyHeader_1_1", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopReplyHeader11 struct {
	GiopReplyHeader10
}

//noinspection GoSnakeCaseUsage
const GiopReplyHeader11Id_Const = "IDL:GIOP/ReplyHeader_1_1:1.0"

func (self *GiopReplyHeader11) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopReplyHeader11) GoString() string {
	return self.String()
}

func (self *GiopReplyHeader11) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.GiopReplyHeader10.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopReplyHeader11) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopReplyHeader11) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.GiopReplyHeader10.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopReplyHeader11_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopReplyHeader11Helper = GiopReplyHeader11_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopReplyHeader11Id_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopReplyHeader11.go",
			func() __goidl__.IIdlObject {
				return &GiopReplyHeader11{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopReplyHeader11{}
			},
			__reflect__.TypeOf((*GiopReplyHeader11)(nil))))
}
