// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"

// Enum declaration: "GIOP::ReplyStatusType_1_0", generatedBy by: "WriteEnumDcl"
type GiopReplyStatusType10 uint32

//noinspection GoUnusedConst
const (
	GiopReplyStatusType10NoException     GiopReplyStatusType10 = 0
	GiopReplyStatusType10UserException   GiopReplyStatusType10 = 1
	GiopReplyStatusType10SystemException GiopReplyStatusType10 = 2
	GiopReplyStatusType10LocationForward GiopReplyStatusType10 = 3
)

//noinspection GoSnakeCaseUsage
type GiopReplyStatusType10_Helper struct {
}

//noinspection GoSnakeCaseUsage
const GiopReplyStatusType10Id_Const = "IDL:omg.org/GIOP/ReplyStatusType_1_0:1.0"

func (self GiopReplyStatusType10_Helper) Id() string {
	return GiopReplyStatusType10Id_Const
}

func (self GiopReplyStatusType10_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self GiopReplyStatusType10_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var GiopReplyStatusType10Helper = GiopReplyStatusType10_Helper{}

func init() {
}
