// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"

// Enum declaration: "GIOP::MsgType_1_1", generatedBy by: "WriteEnumDcl"
type GiopMsgType11 uint32

//noinspection GoUnusedConst
const (
	GiopMsgType11Request         GiopMsgType11 = 0
	GiopMsgType11Reply           GiopMsgType11 = 1
	GiopMsgType11CancelRequest   GiopMsgType11 = 2
	GiopMsgType11LocateRequest   GiopMsgType11 = 3
	GiopMsgType11LocateReply     GiopMsgType11 = 4
	GiopMsgType11CloseConnection GiopMsgType11 = 5
	GiopMsgType11MessageError    GiopMsgType11 = 6
	GiopMsgType11Fragment        GiopMsgType11 = 7
)

//noinspection GoSnakeCaseUsage
type GiopMsgType11_Helper struct {
}

//noinspection GoSnakeCaseUsage
const GiopMsgType11Id_Const = "IDL:omg.org/GIOP/MsgType_1_1:1.0"

func (self GiopMsgType11_Helper) Id() string {
	return GiopMsgType11Id_Const
}

func (self GiopMsgType11_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self GiopMsgType11_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var GiopMsgType11Helper = GiopMsgType11_Helper{}

func init() {
}
