// Code generated by me. DO NOT EDIT.

package goIdlGiop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "GIOP::SystemExceptionReplyBody", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type GiopSystemExceptionReplyBody struct {
	__goidl__.IdlObject
	ExceptionId string `json:"ExceptionId"`
	MinorCodeValue uint32 `json:"MinorCodeValue"`
	CompletionStatus uint32 `json:"CompletionStatus"`
}

//noinspection GoSnakeCaseUsage
const GiopSystemExceptionReplyBodyId_Const = "IDL:omg.org/GIOP/SystemExceptionReplyBody:1.0"

func (self *GiopSystemExceptionReplyBody) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *GiopSystemExceptionReplyBody) GoString() string {
	return self.String()
}

func (self *GiopSystemExceptionReplyBody) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.ExceptionId, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.MinorCodeValue, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.CompletionStatus, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopSystemExceptionReplyBody) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *GiopSystemExceptionReplyBody) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.ExceptionId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.MinorCodeValue)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.CompletionStatus)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type GiopSystemExceptionReplyBody_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var GiopSystemExceptionReplyBodyHelper = GiopSystemExceptionReplyBody_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			GiopSystemExceptionReplyBodyId_Const,
			__goidl__.StructType,
			"GIOP.idl",
			"xdl_GiopSystemExceptionReplyBody.go",
			func() __goidl__.IIdlObject {
				return &GiopSystemExceptionReplyBody{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &GiopSystemExceptionReplyBody{}
			},
			__reflect__.TypeOf((*GiopSystemExceptionReplyBody)(nil))))
}
